BEGIN TRANSACTION;

CREATE TABLE users (
  id serial PRIMARY KEY,
  name VARCHAR(100),
  email text UNIQUE NOT NULL,
  entries BIGINT DEFAULT 0,
  joined TIMESTAMP NOT NULL,
  age SMALLINT NOT NULL CHECK (AGE BETWEEN 0 AND 150),
  pet VARCHAR(100) 
);

COMMIT;